const countries = {
    "en-GB": "English (UK)",
    "en-US": "English (US)",
    "hi-IN": "Hindi",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "de-DE": "German",
    "it-IT": "Italian",
    "pt-PT": "Portuguese",
    "pt-BR": "Portuguese (Brazil)",
    "ru-RU": "Russian",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "ar-SA": "Arabic",
    "bn-BD": "Bengali",
    "ur-PK": "Urdu",
    "tr-TR": "Turkish",
    "vi-VN": "Vietnamese",
    "th-TH": "Thai",
    "nl-NL": "Dutch",
    "sv-SE": "Swedish",
    "pl-PL": "Polish",
    "uk-UA": "Ukrainian",
    "el-GR": "Greek",
    "he-IL": "Hebrew",
    "id-ID": "Indonesian",
    "ms-MY": "Malay",
    "fa-IR": "Persian",
    "ta-IN": "Tamil",
    "te-IN": "Telugu",
    "mr-IN": "Marathi",
    "gu-IN": "Gujarati",
    "kn-IN": "Kannada",
    "ml-IN": "Malayalam",
    "pa-IN": "Punjabi",
    "or-IN": "Odia",
    "as-IN": "Assamese",
    "ne-NP": "Nepali",
    "si-LK": "Sinhala",
    "sw-KE": "Swahili",
    "ro-RO": "Romanian",
    "hu-HU": "Hungarian",
    "cs-CZ": "Czech",
    "sk-SK": "Slovak",
    "fi-FI": "Finnish",
    "no-NO": "Norwegian",
    "da-DK": "Danish",
    "bg-BG": "Bulgarian",
    "sr-RS": "Serbian",
    "hr-HR": "Croatian",
    "sl-SI": "Slovenian",
    "lt-LT": "Lithuanian",
    "lv-LV": "Latvian",
    "et-EE": "Estonian",
    "ka-GE": "Georgian",
    "am-ET": "Amharic",
    "az-AZ": "Azerbaijani",
    "uz-UZ": "Uzbek",
    "km-KH": "Khmer",
    "lo-LA": "Lao",
    "my-MM": "Burmese",
    "mn-MN": "Mongolian",
    "ps-AF": "Pashto",
    "ku-TR": "Kurdish",
    "so-SO": "Somali",
    "zu-ZA": "Zulu",
    "af-ZA": "Afrikaans",
    "is-IS": "Icelandic",
    "mt-MT": "Maltese",
    "ga-IE": "Irish",
    "cy-GB": "Welsh",
    "eu-ES": "Basque",
    "ca-ES": "Catalan",
    "gl-ES": "Galician"
};